### PR TITLE
Center image shields

### PR DESCRIPTION
**Pull request by Exortions**

### CODE REVIEW

**Review by othneildrew — CHANGES_REQUESTED** [review]
Hey, thanks for your contribution! It looks like there is a typo at line 23,1. Remove the [ there and replace the h1 with a div so I can merge.

**Comment by Exortions** [comment]
Alright one second

**Comment by othneildrew** [comment]
Oops, looks like I was run on the `div` tag. it's not rendering properly on github. Change it back to whatever works and I'll go ahead and merge it now!

**Comment by Exortions** [comment]
Okay thanks!

**Comment by Exortions** [comment]
I made a new pr, you can view it here: https://github.com/othneildrew/Best-README-Template/pull/48

**Pull request closed without merging**
